### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by fschon** [balena-io-playground/sdr-spectrum-monitor#1]
Hi, I have followed all the instructions and the build fails with:

[Info]     Starting build for RTL-SDR, user g_franz_sch_ning
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1576877/devices
[Info]     Building on arm01
[Info]     Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[main]     Step 1/15 : FROM balenalib/raspberry-pi2-python:2-build
[main]      ---> fa02420d4e0a
[main]     Step 2/15 : RUN apt-get update
[main]     Using cache
[main]      ---> 940a2b7cdc8e
[main]     Step 3/15 : RUN apt-get -y install libfftw3-dev cmake libusb-1.0-0-dev
[main]     Using cache
[main]      ---> 68798bbbf3e5
[main]     Step 4/15 : RUN apt install netcat
[main]     Using cache
[main]      ---> 64823f6da7da
[main]     Step 5/15 : RUN mkdir -p /tmp
[main]     Using cache
[main]      ---> 69c260cd5eb7
[main]     Step 6/15 : COPY fft_fftw.c /tmp/fft_fftw.c
[main]     Using cache
[main]      ---> 41c513730b49
[main]     Step 7/15 : COPY fft_fftw.h /tmp/fft_fftw.h
[main]     Using cache
[main]      ---> 6f6ecc8aaad3
[main]     Step 8/15 : COPY Makefile /tmp/Makefile
[main]     Using cache
[main]      ---> 86f0cdde9b1f
[main]     Step 9/15 : COPY install.sh /usr/src/app/install.sh
[main]     Using cache
[main]      ---> 270d3ad7df35
[main]     Step 10/15 : RUN ["chmod", "+x", "/usr/src/app/install.sh"]
[main]     Using cache
[main]      ---> 6d44b24a987a
[main]     Step 11/15 : RUN ["/usr/src/app/install.sh"]
[main]      ---> Running in 1091d640d3d6
[main]     standard_init_linux.go:207: exec user process caused "no such file or directory"
[main]
[main]     Removing intermediate container 1091d640d3d6
[main]     The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Uploading images
[Success]  Successfully uploaded images
[Error]    Some services failed to build:
[Error]      Service: main
[Error]        Error: The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Built on arm01
[Error]    Not deploying release.
Remote build failed

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, or "export DEBUG=1"
on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

**Comment by kn4oqw-clint** [comment]
I have the same. I followed the main tutorial located here: https://www.balena.io/blog/running-openwebrx-on-balena-to-remotely-monitor-local-radio-spectrum/


[Info]     Starting build for SDR_Monitor, user gh_chancellor1101
[Info]     Dashboard link: https://dashboard.balena-cloud.com/apps/1601700/devices
[Info]     Building on arm03
[Info]     Pulling previous images for caching purposes...
[Success]  Successfully pulled cache images
[main]     Step 1/15 : FROM balenalib/raspberrypi3-python:2-build
[main]      ---> fa02420d4e0a
[main]     Step 2/15 : RUN apt-get update
[main]      ---> Running in a23eb4c64337
[main]     Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
[main]     Get:2 http://deb.debian.org/debian buster-updates InRelease [49.3 kB]
[main]     Get:3 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
[main]     Get:4 http://deb.debian.org/debian buster/main armhf Packages [7699 kB]
[main]     Get:5 http://deb.debian.org/debian buster-updates/main armhf Packages [7356 B]
[main]     Get:6 http://archive.raspberrypi.org/debian buster InRelease [25.1 kB]
[main]     Get:7 http://archive.raspbian.org/raspbian buster InRelease [15.0 kB]
[main]     Get:8 http://security.debian.org/debian-security buster/updates/main armhf Packages [179 kB]
[main]     Get:9 http://archive.raspberrypi.org/debian buster/main armhf Packages [279 kB]
[main]     Get:10 http://archive.raspbian.org/raspbian buster/main armhf Packages [13.0 MB]
[main]     Get:11 http://archive.raspbian.org/raspbian buster/non-free armhf Packages [103 kB]
[main]     Get:12 http://archive.raspbian.org/raspbian buster/rpi armhf Packages [1360 B]
[main]     Get:13 http://archive.raspbian.org/raspbian buster/contrib armhf Packages [58.7 kB]
[main]     Get:14 http://archive.raspbian.org/raspbian buster/firmware armhf Packages [1232 B]
[main]     Fetched 21.6 MB in 5s (4073 kB/s)
[main]     Reading package lists...
[main]     Removing intermediate container a23eb4c64337
[main]      ---> 99f379262fe6
[main]     Step 3/15 : RUN apt-get -y install libfftw3-dev cmake libusb-1.0-0-dev
[main]      ---> Running in dfcdfa3c1de9
[main]     Reading package lists...
[main]     Building dependency tree...
[main]     Reading state information...
[main]     The following additional packages will be installed:
[main]       cmake-data libarchive13 libfftw3-bin libfftw3-single3 libjsoncpp1 librhash0
[main]       libuv1
[main]     Suggested packages:
[main]       cmake-doc ninja-build lrzip libfftw3-doc
[main]     Recommended packages:
[main]       libusb-1.0-doc
[main]     The following NEW packages will be installed:
[main]       cmake cmake-data libarchive13 libfftw3-bin libfftw3-dev libfftw3-single3
[main]       libjsoncpp1 librhash0 libusb-1.0-0-dev libuv1
[main]     0 upgraded, 10 newly installed, 0 to remove and 107 not upgraded.
[main]     Need to get 6871 kB of archives.
[main]     After this operation, 25.3 MB of additional disk space will be used.
[main]     Get:1 http://deb.debian.org/debian buster/main armhf cmake-data all 3.13.4-1 [1476 kB]
[main]     Get:2 http://deb.debian.org/debian buster/main armhf libarchive13 armhf 3.3.3-4+deb10u1 [277 kB]
[main]     Get:3 http://deb.debian.org/debian buster/main armhf libjsoncpp1 armhf 1.7.4-3 [67.8 kB]
[main]     Get:4 http://deb.debian.org/debian buster/main armhf librhash0 armhf 1.3.8-1 [134 kB]
[main]     Get:5 http://deb.debian.org/debian buster/main armhf libuv1 armhf 1.24.1-1 [98.0 kB]
[main]     Get:6 http://deb.debian.org/debian buster/main armhf cmake armhf 3.13.4-1 [2848 kB]
[main]     Get:7 http://deb.debian.org/debian buster/main armhf libfftw3-single3 armhf 3.3.8-2 [715 kB]
[main]     Get:8 http://deb.debian.org/debian buster/main armhf libfftw3-bin armhf 3.3.8-2 [43.5 kB]
[main]     Get:9 http://deb.debian.org/debian buster/main armhf libfftw3-dev armhf 3.3.8-2 [1141 kB]
[main]     Get:10 http://deb.debian.org/debian buster/main armhf libusb-1.0-0-dev armhf 2:1.0.22-2 [70.7 kB]
[main]     debconf: delaying package configuration, since apt-utils is not installed
[main]
[main]     Fetched 6871 kB in 0s (45.1 MB/s)
[main]     Selecting previously unselected package cmake-data.
[main]     (Reading database ...
(Reading database ... 35%ase ... 5%
(Reading database ... 70%ase ... 40%
[main]     (Reading database ... 75%
[main]     (Reading database ... 80%
[main]     (Reading database ... 85%
[main]     (Reading database ... 90%
[main]     (Reading database ... 95%
(Reading database ... 20165 files and directories currently installed.)
[main]     Preparing to unpack .../0-cmake-data_3.13.4-1_all.deb ...
[main]     Unpacking cmake-data (3.13.4-1) ...
[main]     Selecting previously unselected package libarchive13:armhf.
[main]     Preparing to unpack .../1-libarchive13_3.3.3-4+deb10u1_armhf.deb ...
[main]     Unpacking libarchive13:armhf (3.3.3-4+deb10u1) ...
[main]     Selecting previously unselected package libjsoncpp1:armhf.
[main]     Preparing to unpack .../2-libjsoncpp1_1.7.4-3_armhf.deb ...
[main]     Unpacking libjsoncpp1:armhf (1.7.4-3) ...
[main]     Selecting previously unselected package librhash0:armhf.
[main]     Preparing to unpack .../3-librhash0_1.3.8-1_armhf.deb ...
[main]     Unpacking librhash0:armhf (1.3.8-1) ...
[main]     Selecting previously unselected package libuv1:armhf.
[main]     Preparing to unpack .../4-libuv1_1.24.1-1_armhf.deb ...
[main]     Unpacking libuv1:armhf (1.24.1-1) ...
[main]     Selecting previously unselected package cmake.
[main]     Preparing to unpack .../5-cmake_3.13.4-1_armhf.deb ...
[main]     Unpacking cmake (3.13.4-1) ...
[main]     Selecting previously unselected package libfftw3-single3:armhf.
[main]     Preparing to unpack .../6-libfftw3-single3_3.3.8-2_armhf.deb ...
[main]     Unpacking libfftw3-single3:armhf (3.3.8-2) ...
[main]     Selecting previously unselected package libfftw3-bin.
[main]     Preparing to unpack .../7-libfftw3-bin_3.3.8-2_armhf.deb ...
[main]     Unpacking libfftw3-bin (3.3.8-2) ...
[main]     Selecting previously unselected package libfftw3-dev:armhf.
[main]     Preparing to unpack .../8-libfftw3-dev_3.3.8-2_armhf.deb ...
[main]     Unpacking libfftw3-dev:armhf (3.3.8-2) ...
[main]     Selecting previously unselected package libusb-1.0-0-dev:armhf.
[main]     Preparing to unpack .../9-libusb-1.0-0-dev_2%3a1.0.22-2_armhf.deb ...
[main]     Unpacking libusb-1.0-0-dev:armhf (2:1.0.22-2) ...
[main]     Setting up libfftw3-single3:armhf (3.3.8-2) ...
[main]     Setting up libarchive13:armhf (3.3.3-4+deb10u1) ...
[main]     Setting up libfftw3-bin (3.3.8-2) ...
[main]     Setting up libusb-1.0-0-dev:armhf (2:1.0.22-2) ...
[main]     Setting up libuv1:armhf (1.24.1-1) ...
[main]     Setting up librhash0:armhf (1.3.8-1) ...
[main]     Setting up cmake-data (3.13.4-1) ...
[main]     Setting up libfftw3-dev:armhf (3.3.8-2) ...
[main]     Setting up libjsoncpp1:armhf (1.7.4-3) ...
[main]     Setting up cmake (3.13.4-1) ...
[main]     Processing triggers for libc-bin (2.28-10) ...
[main]     Removing intermediate container dfcdfa3c1de9
[main]      ---> 266dd2a2a251
[main]     Step 4/15 : RUN apt install netcat
[main]      ---> Running in e969aa822a0f
[main]
[main]     WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
[main]
[main]     Reading package lists...
[main]     Building dependency tree...
[main]     Reading state information...
[main]     The following additional packages will be installed:
[main]       netcat-traditional
[main]     The following NEW packages will be installed:
[main]       netcat netcat-traditional
[main]     0 upgraded, 2 newly installed, 0 to remove and 107 not upgraded.
[main]     Need to get 74.7 kB of archives.
[main]     After this operation, 146 kB of additional disk space will be used.
[main]     Get:1 http://deb.debian.org/debian buster/main armhf netcat-traditional armhf 1.10-41.1 [65.6 kB]
[main]     Get:2 http://deb.debian.org/debian buster/main armhf netcat all 1.10-41.1 [9034 B]
[main]     debconf: delaying package configuration, since apt-utils is not installed
[main]
[main]     Fetched 74.7 kB in 1s (61.7 kB/s)
[main]     Selecting previously unselected package netcat-traditional.
[main]     (Reading database ...
(Reading database ... 25%ase ... 5%
(Reading database ... 35%ase ... 30%
(Reading database ... 45%ase ... 40%
(Reading database ... 70%ase ... 50%
[main]     (Reading database ... 75%
[main]     (Reading database ... 80%
[main]     (Reading database ... 85%
[main]     (Reading database ... 90%
[main]     (Reading database ... 95%
(Reading database ... 22805 files and directories currently installed.)
[main]     Preparing to unpack .../netcat-traditional_1.10-41.1_armhf.deb ...
[main]     Unpacking netcat-traditional (1.10-41.1) ...
[main]     Selecting previously unselected package netcat.
[main]     Preparing to unpack .../netcat_1.10-41.1_all.deb ...
[main]     Unpacking netcat (1.10-41.1) ...
[main]     Setting up netcat-traditional (1.10-41.1) ...
[main]     update-alternatives: using /bin/nc.traditional to provide /bin/nc (nc) in auto mode
[main]     update-alternatives: warning: skip creation of /usr/share/man/man1/nc.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist
[main]     update-alternatives: warning: skip creation of /usr/share/man/man1/netcat.1.gz because associated file /usr/share/man/man1/nc.traditional.1.gz (of link group nc) doesn't exist
[main]     Setting up netcat (1.10-41.1) ...
[main]     Removing intermediate container e969aa822a0f
[main]      ---> 8b6c7b771350
[main]     Step 5/15 : RUN mkdir -p /tmp
[main]      ---> Running in 251f12d127be
[main]     Removing intermediate container 251f12d127be
[main]      ---> b0cd52204edc
[main]     Step 6/15 : COPY fft_fftw.c /tmp/fft_fftw.c
[main]      ---> 5b24fe20e97a
[main]     Step 7/15 : COPY fft_fftw.h /tmp/fft_fftw.h
[main]      ---> f5ceb1b25c9d
[main]     Step 8/15 : COPY Makefile /tmp/Makefile
[main]      ---> 73bde96c8de4
[main]     Step 9/15 : COPY install.sh /usr/src/app/install.sh
[main]      ---> f77347757e2d
[main]     Step 10/15 : RUN ["chmod", "+x", "/usr/src/app/install.sh"]
[main]      ---> Running in aa58dc461228
[main]     Removing intermediate container aa58dc461228
[main]      ---> c290fc9cc015
[main]     Step 11/15 : RUN ["/usr/src/app/install.sh"]
[main]      ---> Running in 9cdbefeb52eb
[main]     standard_init_linux.go:207: exec user process caused "no such file or directory"
[main]
[main]     Removing intermediate container 9cdbefeb52eb
[main]     The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Uploading images
[Success]  Successfully uploaded images
[Error]    Some services failed to build:
[Error]      Service: main
[Error]        Error: The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Built on arm03
[Error]    Not deploying release.
Remote build failed

Additional information may be available by setting a DEBUG=1 environment
variable: "set DEBUG=1" on a Windows command prompt, "$env:DEBUG = 1" on
powershell, or "export DEBUG=1" on Linux or macOS.

If you need help, don't hesitate in contacting our support forums at
https://forums.balena.io

For CLI bug reports or feature requests, have a look at the GitHub issues or
create a new one at: https://github.com/balena-io/balena-cli/issues/

**Comment by doodlewhale** [comment]
I have excatly the same. Any fix yet?

[main]     Step 12/16 : RUN ["/usr/src/app/install.sh"]
[main]      ---> Running in 81b96150849b
[main]     standard_init_linux.go:207: exec user process caused "no such file or directory"
[main]     
[main]     Removing intermediate container 81b96150849b
[main]     The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Uploading images
[Success]  Successfully uploaded images
[Error]    Some services failed to build:
[Error]      Service: main
[Error]        Error: The command '/usr/src/app/install.sh' returned a non-zero code: 1
[Info]     Built on arm01
[Error]    Not deploying release.
[Warn]    Windows-format line endings were detected in some files. Consider using the `--convert-eol` option.
Remote build failed

**Comment by doodlewhale** [comment]
I have fixed it for me, and get the unicorn! This appears to be an issue with how 'git clone' on a windows OS changes line endings. I downloaded the zip file instead of cloning with git and it now works.

**Comment by alanb128** [comment]
Downloading the zip file is one option, but also note that balena CLI versions 11.25.0 or later will print a warning if Windows-format line endings are detected. In that case use the `--convert-eol` option when pushing code.
